import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:project/models/ingredient_model.dart';
import 'package:project/services/ingredient_service.dart';

class IngredientPage extends StatefulWidget {
  final bool isRestaurantSide;
  final Function(List<IngredientModel>)? onIngredientsSelected;
  final List<IngredientModel>? initiallySelectedIngredients;

  const IngredientPage({
    super.key,
    this.isRestaurantSide = true,
    this.onIngredientsSelected,
    this.initiallySelectedIngredients,
  });

  @override
  State<IngredientPage> createState() => _IngredientPageState();
}

class _IngredientPageState extends State<IngredientPage> {
  final TextEditingController _searchController = TextEditingController();
  final Map<String, bool> _expandedCategories = {};
  final IngredientService _ingredientService = IngredientService();
  String _searchQuery = "";
  bool _isLoading = false;
  
  // For user side selection
  final Map<String, bool> _selectedIngredients = {};
  
  // For restaurant side - add new ingredient
  final TextEditingController _nameController = TextEditingController();
  final TextEditingController _priceController = TextEditingController();
  final TextEditingController _caloriesController = TextEditingController();
  final TextEditingController _proteinController = TextEditingController();
  final TextEditingController _quantityController = TextEditingController();
  String _selectedCategory = 'Vegetables';
  String _selectedUnit = 'kg';
  String _selectedIcon = 'carrot';

  // Icon mapping
  IconData _getIconData(String iconName) {
    final iconMap = <String, IconData>{
      'bowl_rice': FontAwesomeIcons.bowlRice,
      'bowl_food': FontAwesomeIcons.bowlFood,
      'drumstick_bite': FontAwesomeIcons.drumstickBite,
      'cube': FontAwesomeIcons.cube,
      'pepper_hot': FontAwesomeIcons.pepperHot,
      'seedling': FontAwesomeIcons.seedling,
      'carrot': FontAwesomeIcons.carrot,
      'leaf': FontAwesomeIcons.leaf,
      'apple_whole': FontAwesomeIcons.appleWhole,
      'wheat_awn': FontAwesomeIcons.wheatAwn,
      'fish': FontAwesomeIcons.fish,
      'egg': FontAwesomeIcons.egg,
      'shrimp': FontAwesomeIcons.shrimp,
      'mug_hot': FontAwesomeIcons.mugHot,
      'cheese': FontAwesomeIcons.cheese,
      'mortar_pestle': FontAwesomeIcons.mortarPestle,
    };
    return iconMap[iconName] ?? FontAwesomeIcons.seedling;
  }

  @override
  void initState() {
    super.initState();
    _searchController.addListener(() {
      setState(() {
        _searchQuery = _searchController.text.toLowerCase();
      });
    });
    
    // Initialize selected ingredients for user side
    if (!widget.isRestaurantSide && widget.initiallySelectedIngredients != null) {
      for (final ingredient in widget.initiallySelectedIngredients!) {
        _selectedIngredients[ingredient.id] = true;
      }
    }
  }

  @override
  void dispose() {
    _searchController.dispose();
    _nameController.dispose();
    _priceController.dispose();
    _caloriesController.dispose();
    _proteinController.dispose();
    _quantityController.dispose();
    super.dispose();
  }

  // Update quantity in Firebase (Restaurant side)
  Future<void> _updateQuantity(IngredientModel ingredient, double amount) async {
    try {
      final newQuantity = (ingredient.quantityAvailable + amount).clamp(0.0, double.infinity);
      await _ingredientService.updateIngredientQuantity(ingredient.id, newQuantity);
      
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('${ingredient.name} quantity updated to ${newQuantity.toStringAsFixed(1)} ${ingredient.unit}'),
            duration: const Duration(seconds: 2),
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error updating quantity: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    }
  }

  // Add new ingredient (Restaurant side)
  Future<void> _addNewIngredient() async {
    if (_nameController.text.isEmpty || _priceController.text.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Please fill in name and price'),
          backgroundColor: Colors.red,
        ),
      );
      return;
    }

    setState(() => _isLoading = true);
    try {
      final newIngredient = IngredientModel(
        id: '', // Will be generated by Firestore
        name: _nameController.text,
        category: _selectedCategory,
        price: double.parse(_priceController.text),
        calories: double.parse(_caloriesController.text.isEmpty ? '0' : _caloriesController.text),
        protein: double.parse(_proteinController.text.isEmpty ? '0' : _proteinController.text),
        unit: _selectedUnit,
        quantityAvailable: double.parse(_quantityController.text.isEmpty ? '0' : _quantityController.text),
        iconName: _selectedIcon,
        restaurantId: FirebaseAuth.instance.currentUser!.uid,
        createdAt: DateTime.now(),
      );

      await _ingredientService.addIngredient(newIngredient);
      
      // Clear form
      _nameController.clear();
      _priceController.clear();
      _caloriesController.clear();
      _proteinController.clear();
      _quantityController.clear();
      
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Ingredient added successfully!')),
        );
        Navigator.of(context).pop(); // Close dialog
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error adding ingredient: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  // Show add ingredient dialog (Restaurant side)
  void _showAddIngredientDialog() {
    showDialog(
      context: context,
      builder: (context) => StatefulBuilder(
        builder: (context, setDialogState) {
          return AlertDialog(
            title: Text(
              'Add New Ingredient',
              style: GoogleFonts.lato(fontWeight: FontWeight.bold),
            ),
            content: SingleChildScrollView(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  TextField(
                    controller: _nameController,
                    decoration: const InputDecoration(
                      labelText: 'Ingredient Name',
                      border: OutlineInputBorder(),
                    ),
                  ),
                  const SizedBox(height: 12),
                  Row(
                    children: [
                      Expanded(
                        child: DropdownButtonFormField<String>(
                          initialValue: _selectedCategory,
                          decoration: const InputDecoration(
                            labelText: 'Category',
                            border: OutlineInputBorder(),
                          ),
                          items: const [
                            DropdownMenuItem(value: 'Vegetables', child: Text('Vegetables')),
                            DropdownMenuItem(value: 'Fruits', child: Text('Fruits')),
                            DropdownMenuItem(value: 'Meat', child: Text('Meat')),
                            DropdownMenuItem(value: 'Dairy', child: Text('Dairy')),
                            DropdownMenuItem(value: 'Grains', child: Text('Grains')),
                            DropdownMenuItem(value: 'Spices', child: Text('Spices')),
                            DropdownMenuItem(value: 'Seafood', child: Text('Seafood')),
                            DropdownMenuItem(value: 'Others', child: Text('Others')),
                          ],
                          onChanged: (value) {
                            setDialogState(() {
                              _selectedCategory = value!;
                            });
                          },
                        ),
                      ),
                      const SizedBox(width: 12),
                      Expanded(
                        child: DropdownButtonFormField<String>(
                          initialValue: _selectedUnit,
                          decoration: const InputDecoration(
                            labelText: 'Unit',
                            border: OutlineInputBorder(),
                          ),
                          items: const [
                            DropdownMenuItem(value: 'kg', child: Text('kg')),
                            DropdownMenuItem(value: 'g', child: Text('g')),
                            DropdownMenuItem(value: 'lb', child: Text('lb')),
                            DropdownMenuItem(value: 'piece', child: Text('piece')),
                            DropdownMenuItem(value: 'bunch', child: Text('bunch')),
                            DropdownMenuItem(value: 'liter', child: Text('liter')),
                            DropdownMenuItem(value: 'ml', child: Text('ml')),
                          ],
                          onChanged: (value) {
                            setDialogState(() {
                              _selectedUnit = value!;
                            });
                          },
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 12),
                  TextField(
                    controller: _priceController,
                    decoration: const InputDecoration(
                      labelText: 'Price per unit',
                      border: OutlineInputBorder(),
                      prefixText: '₹',
                    ),
                    keyboardType: TextInputType.number,
                  ),
                  const SizedBox(height: 12),
                  Row(
                    children: [
                      Expanded(
                        child: TextField(
                          controller: _caloriesController,
                          decoration: const InputDecoration(
                            labelText: 'Calories',
                            border: OutlineInputBorder(),
                            suffixText: 'kcal',
                          ),
                          keyboardType: TextInputType.number,
                        ),
                      ),
                      const SizedBox(width: 12),
                      Expanded(
                        child: TextField(
                          controller: _proteinController,
                          decoration: const InputDecoration(
                            labelText: 'Protein',
                            border: OutlineInputBorder(),
                            suffixText: 'g',
                          ),
                          keyboardType: TextInputType.number,
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 12),
                  TextField(
                    controller: _quantityController,
                    decoration: const InputDecoration(
                      labelText: 'Initial Quantity',
                      border: OutlineInputBorder(),
                    ),
                    keyboardType: TextInputType.number,
                  ),
                  const SizedBox(height: 12),
                  DropdownButtonFormField<String>(
                    initialValue: _selectedIcon,
                    decoration: const InputDecoration(
                      labelText: 'Icon',
                      border: OutlineInputBorder(),
                    ),
                    items: const [
                      DropdownMenuItem(value: 'carrot', child: Text('Carrot')),
                      DropdownMenuItem(value: 'apple_whole', child: Text('Apple')),
                      DropdownMenuItem(value: 'drumstick_bite', child: Text('Meat')),
                      DropdownMenuItem(value: 'fish', child: Text('Fish')),
                      DropdownMenuItem(value: 'egg', child: Text('Egg')),
                      DropdownMenuItem(value: 'cheese', child: Text('Cheese')),
                      DropdownMenuItem(value: 'wheat_awn', child: Text('Grain')),
                      DropdownMenuItem(value: 'pepper_hot', child: Text('Spice')),
                      DropdownMenuItem(value: 'bowl_rice', child: Text('Rice')),
                      DropdownMenuItem(value: 'mug_hot', child: Text('Liquid')),
                    ],
                    onChanged: (value) {
                      setDialogState(() {
                        _selectedIcon = value!;
                      });
                    },
                  ),
                ],
              ),
            ),
            actions: [
              TextButton(
                onPressed: () => Navigator.of(context).pop(),
                child: const Text('Cancel'),
              ),
              ElevatedButton(
                onPressed: _isLoading ? null : _addNewIngredient,
                child: _isLoading 
                    ? const SizedBox(
                        height: 16,
                        width: 16,
                        child: CircularProgressIndicator(strokeWidth: 2),
                      )
                    : const Text('Add Ingredient'),
              ),
            ],
          );
        },
      ),
    );
  }

  // Toggle ingredient selection (User side)
  void _toggleIngredientSelection(IngredientModel ingredient) {
    setState(() {
      if (_selectedIngredients.containsKey(ingredient.id)) {
        _selectedIngredients.remove(ingredient.id);
      } else {
        _selectedIngredients[ingredient.id] = true;
      }
    });
  }

  // Get selected ingredients (User side)
  List<IngredientModel> _getSelectedIngredients(List<IngredientModel> allIngredients) {
    return allIngredients.where((ingredient) => _selectedIngredients.containsKey(ingredient.id)).toList();
  }

  // Confirm selection (User side)
  void _confirmSelection(List<IngredientModel> allIngredients) {
    final selected = _getSelectedIngredients(allIngredients);
    if (widget.onIngredientsSelected != null) {
      widget.onIngredientsSelected!(selected);
    }
    Navigator.of(context).pop(selected);
  }

  // Seed default ingredients (run once)
  Future<void> _seedIngredients() async {
    setState(() => _isLoading = true);
    try {
      await _ingredientService.seedDefaultIngredients();
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Default ingredients added successfully!')),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error seeding ingredients: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  Map<String, List<IngredientModel>> _groupIngredientsByCategory(
    List<IngredientModel> ingredients,
  ) {
    final Map<String, List<IngredientModel>> grouped = {};
    for (final ingredient in ingredients) {
      if (!grouped.containsKey(ingredient.category)) {
        grouped[ingredient.category] = [];
      }
      grouped[ingredient.category]!.add(ingredient);
    }
    return grouped;
  }

  Widget _buildInventoryControls(IngredientModel ingredient) {
    Color statusColor;
    String statusText;

    if (ingredient.quantityAvailable <= 0.1) {
      statusColor = Colors.red;
      statusText = 'OUT OF STOCK';
    } else if (ingredient.quantityAvailable <= 5.0) {
      statusColor = Colors.orange;
      statusText = 'LOW STOCK';
    } else {
      statusColor = Colors.green;
      statusText = 'IN STOCK';
    }

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
              decoration: BoxDecoration(
                color: statusColor.withOpacity(0.1),
                borderRadius: BorderRadius.circular(4),
                border: Border.all(color: statusColor, width: 0.5),
              ),
              child: Text(
                statusText,
                style: GoogleFonts.lato(
                  fontSize: 10,
                  fontWeight: FontWeight.bold,
                  color: statusColor,
                ),
              ),
            ),
            Text(
              'Qty: ${ingredient.quantityAvailable.toStringAsFixed(1)} ${ingredient.unit}',
              style: GoogleFonts.lato(
                fontSize: 14,
                fontWeight: FontWeight.bold,
                color: Colors.blueGrey,
              ),
            ),
          ],
        ),
        const SizedBox(height: 8),
        Row(
          mainAxisAlignment: MainAxisAlignment.end,
          children: [
            IconButton(
              icon: const Icon(Icons.remove_circle_outline, color: Colors.redAccent),
              iconSize: 20,
              onPressed: () => _updateQuantity(ingredient, -1.0),
              tooltip: 'Remove 1 unit',
            ),
            IconButton(
              icon: const Icon(Icons.add_circle_outline, color: Colors.green),
              iconSize: 20,
              onPressed: () => _updateQuantity(ingredient, 1.0),
              tooltip: 'Add 1 unit',
            ),
            IconButton(
              icon: const Icon(Icons.delete_outline, color: Colors.grey),
              iconSize: 20,
              onPressed: () => _showDeleteConfirmation(ingredient),
              tooltip: 'Delete ingredient',
            ),
          ],
        ),
      ],
    );
  }

  void _showDeleteConfirmation(IngredientModel ingredient) {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Delete Ingredient'),
        content: Text('Are you sure you want to delete ${ingredient.name}?'),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(context).pop(),
            child: const Text('Cancel'),
          ),
          TextButton(
            onPressed: () {
              Navigator.of(context).pop();
              _deleteIngredient(ingredient);
            },
            style: TextButton.styleFrom(foregroundColor: Colors.red),
            child: const Text('Delete'),
          ),
        ],
      ),
    );
  }

  Future<void> _deleteIngredient(IngredientModel ingredient) async {
    try {
      await _ingredientService.deleteIngredient(ingredient.id);
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('${ingredient.name} deleted successfully'),
            backgroundColor: Colors.green,
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error deleting ingredient: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    }
  }

  Widget _buildUserSideControls(IngredientModel ingredient) {
    final isSelected = _selectedIngredients.containsKey(ingredient.id);
    final isOutOfStock = ingredient.quantityAvailable <= 0.1;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
              decoration: BoxDecoration(
                color: isOutOfStock ? Colors.red.withOpacity(0.1) : Colors.green.withOpacity(0.1),
                borderRadius: BorderRadius.circular(4),
                border: Border.all(
                  color: isOutOfStock ? Colors.red : Colors.green,
                  width: 0.5,
                ),
              ),
              child: Text(
                isOutOfStock ? 'OUT OF STOCK' : 'AVAILABLE',
                style: GoogleFonts.lato(
                  fontSize: 10,
                  fontWeight: FontWeight.bold,
                  color: isOutOfStock ? Colors.red : Colors.green,
                ),
              ),
            ),
            if (!isOutOfStock)
              IconButton(
                icon: Icon(
                  isSelected ? Icons.check_circle : Icons.radio_button_unchecked,
                  color: isSelected ? Colors.green : Colors.grey,
                ),
                onPressed: () => _toggleIngredientSelection(ingredient),
                tooltip: isSelected ? 'Deselect' : 'Select',
              ),
          ],
        ),
        if (isOutOfStock)
          Padding(
            padding: const EdgeInsets.only(top: 8.0),
            child: Text(
              'Currently unavailable',
              style: GoogleFonts.lato(
                fontSize: 12,
                color: Colors.red,
                fontStyle: FontStyle.italic,
              ),
            ),
          ),
      ],
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(
          widget.isRestaurantSide ? 'Inventory Management' : 'Customize Ingredients',
          style: GoogleFonts.lato(fontWeight: FontWeight.bold),
        ),
        centerTitle: true,
        backgroundColor: Theme.of(context).colorScheme.primary,
        foregroundColor: Theme.of(context).colorScheme.onPrimary,
        actions: [
          if (widget.isRestaurantSide) ...[
            // Add new ingredient button
            IconButton(
              icon: const Icon(Icons.add),
              onPressed: _showAddIngredientDialog,
              tooltip: 'Add New Ingredient',
            ),
            // Seed button (for initial setup)
            IconButton(
              icon: const Icon(Icons.download),
              onPressed: _seedIngredients,
              tooltip: 'Load Default Ingredients',
            ),
          ],
        ],
      ),
      body: Column(
        children: [
          // Search Bar
          Padding(
            padding: const EdgeInsets.all(12.0),
            child: TextField(
              controller: _searchController,
              decoration: InputDecoration(
                hintText: 'Search Ingredients...',
                prefixIcon: const Icon(Icons.search),
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(12),
                ),
                contentPadding: const EdgeInsets.symmetric(
                  vertical: 10.0,
                  horizontal: 15.0,
                ),
              ),
            ),
          ),

          // Selected ingredients count (User side)
          if (!widget.isRestaurantSide && widget.onIngredientsSelected != null)
            StreamBuilder<List<IngredientModel>>(
              stream: _ingredientService.getRestaurantIngredients(),
              builder: (context, snapshot) {
                if (snapshot.hasData) {
                  final selectedCount = _getSelectedIngredients(snapshot.data!).length;
                  return Container(
                    padding: const EdgeInsets.symmetric(vertical: 8, horizontal: 16),
                    color: Colors.blue.withOpacity(0.1),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Text(
                          '$selectedCount ingredients selected',
                          style: GoogleFonts.lato(
                            fontWeight: FontWeight.bold,
                            color: Colors.blue,
                          ),
                        ),
                        ElevatedButton.icon(
                          onPressed: () => _confirmSelection(snapshot.data!),
                          icon: const Icon(Icons.check),
                          label: const Text('Confirm'),
                          style: ElevatedButton.styleFrom(
                            backgroundColor: Colors.green,
                            foregroundColor: Colors.white,
                          ),
                        ),
                      ],
                    ),
                  );
                }
                return const SizedBox();
              },
            ),

          // Ingredient List (Real-time Stream)
          Expanded(
            child: StreamBuilder<List<IngredientModel>>(
              stream: _ingredientService.getRestaurantIngredients(),
              builder: (context, snapshot) {
                if (snapshot.connectionState == ConnectionState.waiting) {
                  return const Center(
                    child: CircularProgressIndicator(),
                  );
                }

                if (snapshot.hasError) {
                  return Center(
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        const Icon(Icons.error_outline, size: 48, color: Colors.red),
                        const SizedBox(height: 16),
                        Text(
                          'Error loading ingredients',
                          style: GoogleFonts.lato(fontSize: 16),
                        ),
                        Text(
                          '${snapshot.error}',
                          style: const TextStyle(color: Colors.red),
                          textAlign: TextAlign.center,
                        ),
                        const SizedBox(height: 16),
                        if (widget.isRestaurantSide)
                          ElevatedButton(
                            onPressed: _seedIngredients,
                            child: const Text('Load Default Ingredients'),
                          ),
                      ],
                    ),
                  );
                }

                if (!snapshot.hasData || snapshot.data!.isEmpty) {
                  return Center(
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        const Icon(Icons.inventory_2_outlined, size: 64, color: Colors.grey),
                        const SizedBox(height: 16),
                        Text(
                          'No ingredients found',
                          style: GoogleFonts.lato(
                            fontSize: 18, 
                            fontWeight: FontWeight.bold
                          ),
                        ),
                        const SizedBox(height: 8),
                        if (widget.isRestaurantSide) ...[
                          const Text('Click the download button to load defaults'),
                          const SizedBox(height: 24),
                          ElevatedButton.icon(
                            onPressed: _seedIngredients,
                            icon: const Icon(Icons.download),
                            label: const Text('Load Default Ingredients'),
                          ),
                        ] else
                          const Text('No ingredients available for customization'),
                      ],
                    ),
                  );
                }

                // Filter ingredients based on search
                final allIngredients = snapshot.data!;
                final filteredIngredients = allIngredients.where((ingredient) {
                  return ingredient.name.toLowerCase().contains(_searchQuery);
                }).toList();

                if (filteredIngredients.isEmpty) {
                  return Center(
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        const Icon(Icons.search_off, size: 64, color: Colors.grey),
                        const SizedBox(height: 16),
                        Text(
                          'No ingredients match "$_searchQuery"',
                          style: GoogleFonts.lato(fontSize: 16),
                        ),
                      ],
                    ),
                  );
                }

                final groupedIngredients = _groupIngredientsByCategory(filteredIngredients);

                // Get sorted categories for consistent ordering
                final sortedCategories = groupedIngredients.keys.toList()..sort();

                // Initialize expansion states for new categories
                for (final category in sortedCategories) {
                  _expandedCategories.putIfAbsent(category, () => true);
                }

                return ListView.builder(
                  itemCount: sortedCategories.length,
                  itemBuilder: (context, index) {
                    final category = sortedCategories[index];
                    final ingredients = groupedIngredients[category]!;

                    return Padding(
                      padding: const EdgeInsets.only(bottom: 8.0),
                      child: ExpansionTile(
                        key: PageStorageKey(category),
                        title: Text(
                          category,
                          style: GoogleFonts.lato(
                            fontSize: 20,
                            fontWeight: FontWeight.bold,
                            color: Theme.of(context).colorScheme.primary,
                          ),
                        ),
                        subtitle: Text(
                          '${ingredients.length} items',
                          style: const TextStyle(fontSize: 12),
                        ),
                        initiallyExpanded: _expandedCategories[category] ?? true,
                        onExpansionChanged: (isExpanded) {
                          setState(() {
                            _expandedCategories[category] = isExpanded;
                          });
                        },
                        children: ingredients.map((ingredient) {
                          return Padding(
                            padding: const EdgeInsets.symmetric(horizontal: 8.0),
                            child: Card(
                              margin: const EdgeInsets.symmetric(
                                horizontal: 8,
                                vertical: 4,
                              ),
                              elevation: 2,
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(8),
                              ),
                              child: Padding(
                                padding: const EdgeInsets.all(12.0),
                                child: Column(
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    ListTile(
                                      contentPadding: EdgeInsets.zero,
                                      leading: FaIcon(
                                        _getIconData(ingredient.iconName),
                                        color: widget.isRestaurantSide 
                                            ? Colors.green
                                            : (_selectedIngredients.containsKey(ingredient.id) 
                                                ? Colors.green 
                                                : Colors.grey),
                                        size: 24,
                                      ),
                                      title: Text(
                                        ingredient.name,
                                        style: GoogleFonts.lato(
                                          fontWeight: FontWeight.w600,
                                          fontSize: 16,
                                        ),
                                      ),
                                      subtitle: Text(
                                        '${ingredient.calories} kcal | ${ingredient.protein}g protein',
                                        style: GoogleFonts.lato(
                                          fontSize: 12,
                                          color: Colors.grey[600],
                                        ),
                                      ),
                                      trailing: Column(
                                        mainAxisAlignment: MainAxisAlignment.center,
                                        crossAxisAlignment: CrossAxisAlignment.end,
                                        children: [
                                          Text(
                                            '₹${ingredient.price.toStringAsFixed(2)}',
                                            style: GoogleFonts.lato(
                                              fontWeight: FontWeight.bold,
                                              fontSize: 16,
                                              color: Colors.redAccent,
                                            ),
                                          ),
                                          Text(
                                            'per ${ingredient.unit}',
                                            style: GoogleFonts.lato(
                                              fontSize: 10,
                                              color: Colors.grey,
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                    const Divider(height: 1, indent: 16, endIndent: 16),
                                    Padding(
                                      padding: const EdgeInsets.symmetric(
                                        horizontal: 16.0,
                                        vertical: 8.0,
                                      ),
                                      child: widget.isRestaurantSide
                                          ? _buildInventoryControls(ingredient)
                                          : _buildUserSideControls(ingredient),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                          );
                        }).toList(),
                      ),
                    );
                  },
                );
              },
            ),
          ),
        ],
      ),
    );
  }
}